# rna_predict/conf/default.yaml
# Main Hydra configuration file for RNA prediction pipeline

defaults:
  - _self_  # Load this file's contents first
  - model/stageA@model.stageA
  - model/stageC@model.stageC
  - model/stageB_torsion@model.stageB.torsion_bert
  - model/stageB_pairformer@model.stageB.pairformer
  - model/stageD_diffusion@stageD_diffusion  # Load stageD_diffusion first
  - model/stageD@model.stageD
  - model/protenix_integration@model.protenix_integration
  - test_data@test_data  # Include test data configuration

# RNA sequence to predict structure for
sequence: ${test_data.sequence}  # Default to test sequence

# Global settings
device: "cpu"  # Global device setting, can be overridden per stage
seed: 42
atoms_per_residue: 44

# Project metadata
# project:
#   name: "RNA_PREDICT"
#   version: "1.0.0"
#   description: "RNA structure prediction pipeline"

# Pipeline settings
pipeline:
  verbose: true
  save_intermediates: true
  output_dir: "outputs"
  ignore_nan_values: true  # Set to true to ignore NaN values and continue pipeline execution
  nan_replacement_value: 0.0  # Value to replace NaNs with when ignore_nan_values is true

# Visualization settings
# visualization:
#   enabled: true
#   format: "png"
#   dpi: 300