# rna_predict/conf/default.yaml
# Main Hydra configuration file for RNA prediction pipeline

defaults:
  - shared: features
  - _self_  # Load this file's contents first
  - data: default
  - model/stageA@model.stageA
  - model/stageC@model.stageC
  - model/stageB_torsion@model.stageB.torsion_bert
  - model/stageB_pairformer@model.stageB.pairformer
  - model/stageD_diffusion@stageD_diffusion  # Load stageD_diffusion first
  - model/stageD@model.stageD
  - model/protenix_integration@model.protenix_integration
  - test_data@test_data  # Include test data configuration

# RNA sequence to predict structure for
sequence: ${test_data.sequence}  # Default to test sequence

# Global settings
device: ${oc.env:DEVICE, cpu}  # Global device setting, can be overridden per stage
seed: 42
atoms_per_residue: 44
# Default backend for torsion extraction; can be overridden via Hydra/CLI
extraction_backend: dssr

# Pipeline stage control flags
run_stageD: true  # Enable Stage D diffusion refinement
enable_stageC: true  # Enable partial coordinates from Stage C
merge_latent: true  # Enable latent merging

# Project metadata
# project:
#   name: "RNA_PREDICT"
#   version: "1.0.0"
#   description: "RNA structure prediction pipeline"

# Pipeline settings
pipeline:
  verbose: true
  save_intermediates: true
  output_dir: "outputs"
  ignore_nan_values: true  # Set to true to ignore NaN values and continue pipeline execution
  nan_replacement_value: 0.0  # Value to replace NaNs with when ignore_nan_values is true

# Visualization settings
# visualization:
#   enabled: true
#   format: "png"
#   dpi: 300

training:
  checkpoint_dir: outputs/checkpoints
  accelerator: cpu   # Trainer accelerator (e.g. 'cpu', 'mps', 'cuda')
  devices: 1         # Number of devices for Trainer
  epochs: 10         # Default number of training epochs
  batch_size: 32     # Default training batch size
  limit_train_batches: 1  # Default number of training batches per epoch (for quick tests)
  streamline_mode: true  # When true, run only TorsionBERT -> Stage C for streamlined training

# Minimal prediction section for Hydra completeness
prediction:
  repeats: 5
  residue_atom_choice: 0
  enable_stochastic_inference_for_submission: false