# rna_predict/conf/model/stageA.yaml
# Corresponds to the StageAConfig dataclass in config_schema.py
# Includes defaults from StageA_2D_Adjacency.md documentation

# --- Top-Level Parameters ---
num_hidden: 128
dropout: 0.3
min_seq_length: 80
device: "cuda" # Specify device as string ("cuda" or "cpu")
checkpoint_path: "RFold/checkpoints/RNAStralign_trainset_pretrained.pth"
checkpoint_url: "[https://www.dropbox.com/s/l04l9bf3v6z2tfd/checkpoints.zip?dl=1](https://www.dropbox.com/s/l04l9bf3v6z2tfd/checkpoints.zip?dl=1)"
batch_size: 32
lr: 0.001
threshold: 0.5

# --- Nested Configurations ---

visualization:
  enabled: true
  varna_jar_path: "tools/varna-3-93.jar"
  resolution: 8.0

model:
  # U-Net Architecture Parameters
  conv_channels: [64, 128, 256, 512]
  residual: true
  c_in: 1
  c_out: 1
  c_hid: 32

  # Seq2Map Parameters (Nested under model)
  seq2map:
    input_dim: 4
    max_length: 3000
    attention_heads: 8
    attention_dropout: 0.1
    positional_encoding: true
    query_key_dim: 128
    expansion_factor: 2.0
    heads: 1 # For OffsetScale

  # Decoder Parameters (Nested under model)
  decoder:
    up_conv_channels: [256, 128, 64]
    skip_connections: true