"""
Protein utilities package for structure manipulation and mask generation.
"""

from rna_predict.pipeline.stageC.mp_nerf.protein_utils.supreme_data import (
    SUPREME_MASK,
)

from .mask_generators import (
    make_atom_token_mask,
    make_bond_mask,
    make_cloud_mask,
    make_idx_mask,
    make_theta_mask,
    make_torsion_mask,
    scn_angle_mask,
    scn_bond_mask,
    scn_cloud_mask,
    scn_index_mask,
    scn_rigid_index_mask,
)
from .sidechain_data import (
    AAS2INDEX,
    AMBIGUOUS,
    INDEX2AAS,
    SC_BUILD_INFO,
    SIDECHAIN_ANGLES,
    SIDECHAIN_BONDS,
    SIDECHAIN_MASK,
    SUPREME_INFO,
)
from .structure_utils import (
    build_scaffolds_from_scn_angles,
    get_angle_names,
    get_angle_types,
    get_angle_values,
    get_atom_names,
    get_bond_names,
    get_bond_types,
    get_bond_values,
    get_rigid_frames,
    get_symmetric_atom_pairs,
    get_torsion_names,
    get_torsion_types,
    get_torsion_values,
    modify_angles_mask_with_torsions,
    modify_scaffolds_with_coords,
    protein_fold,
)

__all__ = [
    "SC_BUILD_INFO",
    "AAS2INDEX",
    "INDEX2AAS",
    "AMBIGUOUS",
    "SUPREME_INFO",
    "SIDECHAIN_ANGLES",
    "SIDECHAIN_BONDS",
    "SIDECHAIN_MASK",
    "get_rigid_frames",
    "get_atom_names",
    "get_bond_names",
    "get_bond_types",
    "get_bond_values",
    "get_angle_names",
    "get_angle_types",
    "get_angle_values",
    "get_torsion_names",
    "get_torsion_types",
    "get_torsion_values",
    "build_scaffolds_from_scn_angles",
    "modify_scaffolds_with_coords",
    "get_symmetric_atom_pairs",
    "modify_angles_mask_with_torsions",
    "protein_fold",
    "SUPREME_MASK",
    "make_cloud_mask",
    "make_bond_mask",
    "make_theta_mask",
    "make_torsion_mask",
    "make_idx_mask",
    "make_atom_token_mask",
    "scn_angle_mask",
    "scn_bond_mask",
    "scn_cloud_mask",
    "scn_index_mask",
    "scn_rigid_index_mask",
]
